---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

## Directories for project-specific LXD container persistent storage
## -----------------------------------------------------------------

- name: Create a directory to mount in module containers
  file:
    path: "/var/containers/{{ project_id }}"
    state: directory
    mode: '0755'


## Copy README into top-level directory for project containers

- name: Copy README
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/containers/{{ project_id }}/README"
    src: README
    force: yes


### Gitea directories

- name: Create a directory for gitea container persistent storage
  file:
    path: /var/containers/{{ project_id }}/gitea
    state: directory
    mode: '0755'

- name: Create a directory for gitea container config
  file:
    path: /var/containers/{{ project_id }}/gitea/config
    state: directory
    mode: '0755'

- name: Create a directory for gitea container data
  file:
    path: /var/containers/{{ project_id }}/gitea/data
    state: directory
    mode: '0755'
